unbind C-b
set -g prefix `
bind ` send-prefix

set -g set-clipboard on
setw -g mode-keys vi
bind ] paste-buffer

# Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# resurrect: also save/restore pane contents
set -g @resurrect-capture-pane-contents 'on'

# continuum: auto-save every 15 min, auto-restore on tmux server start
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

# Keep this line at the very bottom of the file
run '~/.tmux/plugins/tpm/tpm'
